cmake_minimum_required(VERSION 3.20)
project(h5fortran_consumer LANGUAGES C Fortran)
find_package(h5fortran CONFIG REQUIRED)
add_executable(consumer main.F90)
target_link_libraries(consumer PRIVATE h5fortran::h5fortran)
add_executable(serial_component visualization.F90)
target_link_libraries(serial_component PRIVATE h5fortran::h5fortran_serial)
